# Generated by Django 2.1.7 on 2019-03-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0002_remove_produtor_nomeee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pavilhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pav', models.CharField(max_length=255, null=True)),
                ('capacidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='produtor',
            old_name='email',
            new_name='contacto',
        ),
        migrations.AddField(
            model_name='pavilhao',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtor.Produtor'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='pavilhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtor.Pavilhao'),
        ),
    ]
